import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Clock3,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,Share2,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import {Select,SelectContent,SelectItem,SelectTrigger} from '@/components/ui/select';
import AnatomyScene from './scene';
import {EDITIONS,LEARNING_PRESETS,SYSTEMS,EXPLANATIONS,defaultVisible,edition,explanation,type Atlas,type Concept,type LearningPreset,type SceneState,type Sex,type SystemId,type View} from './anatomy';
type Theme='light'|'dark';
type RecentEntry={sex:Sex;id:string;name:string};
const MESSAGE_CHANNEL='testwiz-anatomy',MESSAGE_VERSION=1,GUIDE_KEY='testwiz-anatomy-guide-v1',RECENTS_KEY='testwiz-anatomy-recents-v1';
const parentOrigin=()=>{try{const origin=new URL(document.referrer).origin,host=new URL(origin).hostname;return (origin.startsWith('http://localhost')||origin.startsWith('http://127.0.0.1')||host==='testwiz.ng'||host.endsWith('.testwiz.ng'))?origin:'';}catch{return '';}};
const notifyParent=(payload:Record<string,unknown>)=>{const origin=parentOrigin();if(origin&&window.parent!==window)window.parent.postMessage({channel:MESSAGE_CHANNEL,version:MESSAGE_VERSION,...payload},origin);};
const slug=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const findConcept=(atlas:Atlas,value:string)=>{const query=value.toLowerCase().trim();const key=slug(value);return atlas.concepts.find(c=>c.id.toLowerCase()===query||c.name.toLowerCase()===query||c.id.toLowerCase().endsWith(`:${query}`)||slug(c.name)===key);};
const urlSex=():Sex=>{try{return new URLSearchParams(window.location.search).get('edition')==='female'?'female':'male';}catch{return 'male';}};
const readRecents=():RecentEntry[]=>{try{const value=JSON.parse(localStorage.getItem(RECENTS_KEY)??'[]');return Array.isArray(value)?value.filter((entry):entry is RecentEntry=>!!entry&&(entry.sex==='male'||entry.sex==='female')&&typeof entry.id==='string'&&typeof entry.name==='string').slice(0,8):[];}catch{return [];}};
const VIEW_VALUES:View[]=['three-quarter','front','side','back'];
const STATE_PARAMS=['view','explode','visible','surface','isolate'];
const writeShareUrl=(sex:Sex,structure?:string,viewerState?:SceneState)=>{const url=new URL(window.location.href);if(sex==='male')url.searchParams.delete('edition');else url.searchParams.set('edition',sex);if(structure)url.searchParams.set('structure',slug(structure));else url.searchParams.delete('structure');if(viewerState){if(viewerState.view!=='three-quarter')url.searchParams.set('view',viewerState.view);else url.searchParams.delete('view');if(viewerState.explode>0)url.searchParams.set('explode',String(Math.round(viewerState.explode*100)));else url.searchParams.delete('explode');const defaults=defaultVisible(sex);if(viewerState.visible.join(',')!==defaults.join(','))url.searchParams.set('visible',viewerState.visible.join(','));else url.searchParams.delete('visible');if(sex==='female'&&Math.abs(viewerState.surfaceOpacity-.24)>.005)url.searchParams.set('surface',String(Math.round(viewerState.surfaceOpacity*100)));else url.searchParams.delete('surface');if(viewerState.isolate)url.searchParams.set('isolate','1');else url.searchParams.delete('isolate');}window.history.replaceState(null,'',`${url.pathname}${url.search}${url.hash}`);};
const clearStateParams=()=>{const url=new URL(window.location.href);STATE_PARAMS.forEach(param=>url.searchParams.delete(param));window.history.replaceState(null,'',`${url.pathname}${url.search}${url.hash}`);};
const initial=(sex:Sex):SceneState=>({explode:0,visible:defaultVisible(sex),selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0,surfaceOpacity:sex==='female'?.24:.1});
const fromUrl=(sex:Sex):SceneState=>{const defaults=initial(sex);try{const params=new URLSearchParams(window.location.search),view=params.get('view');const visibleParam=params.get('visible');const visible=visibleParam===null?defaults.visible:visibleParam.split(',').filter((id):id is SystemId=>SYSTEMS.some(system=>system.id===id));const explode=Math.max(0,Math.min(1,Number(params.get('explode')||0)/100));const surface=Math.max(.05,Math.min(.6,Number(params.get('surface')||defaults.surfaceOpacity*100)/100));return {...defaults,view:view&&VIEW_VALUES.includes(view as View)?view as View:defaults.view,visible,explode,surfaceOpacity:sex==='female'?surface:defaults.surfaceOpacity,isolate:params.get('isolate')==='1'};}catch{return defaults;}};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null),deepLinkKey=useRef('');
 const [sex,setSex]=useState<Sex>(urlSex);
 const [theme,setTheme]=useState<Theme>(()=>window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
 const source=edition(sex);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(()=>fromUrl(urlSex())),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[infoSystem,setInfoSystem]=useState<SystemId|null>(null),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null),[recent,setRecent]=useState<RecentEntry[]>(readRecents),[guide,setGuide]=useState(()=>{try{return localStorage.getItem(GUIDE_KEY)!=='dismissed';}catch{return true;}}),[announcement,setAnnouncement]=useState(''),[copied,setCopied]=useState(false);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setInfoSystem(null);setDetails(false);setPanel(null);setQuery('');setState(fromUrl(sex));fetch(source.manifest,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>{if(!abort.signal.aborted)setAtlas(data as Atlas);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[sex,source.manifest]);
 useEffect(()=>{try{localStorage.setItem(RECENTS_KEY,JSON.stringify(recent.slice(0,8)));}catch{}},[recent]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;},[theme]);
 useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.source!==window.parent||!parentOrigin()||event.origin!==parentOrigin())return;const message=event.data;if(message?.channel===MESSAGE_CHANNEL&&message?.version===MESSAGE_VERSION&&message?.type==='theme'&&(message.theme==='light'||message.theme==='dark'))setTheme(message.theme);};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[]);
 useEffect(()=>{notifyParent({type:'progress',progress});},[progress]);
 useEffect(()=>{if(error)notifyParent({type:'error',message:error});},[error]);
 useEffect(()=>{if(!atlas)return;const timer=window.setTimeout(()=>{writeShareUrl(sex,chosen?.name,state);notifyParent({type:'state',sex,url:window.location.href,view:state.view,explode:state.explode,visible:state.visible,selected:state.selected,selectedName:chosen?.name??null});},180);return()=>window.clearTimeout(timer);},[atlas,sex,state.view,state.explode,state.visible,state.selected,state.surfaceOpacity,state.isolate,chosen?.name]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system),info=infoSystem?SYSTEMS.find(s=>s.id===infoSystem):undefined;
 const detailOpen=(details&&selectedParts.length>0)||!!infoSystem;
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return source.suggestions.map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query,source]);
 const recentForEdition=recent.filter(entry=>entry.sex===sex);
 const announce=useCallback((message:string)=>setAnnouncement(message),[]);
 const rememberRecent=useCallback((concept:Concept)=>setRecent(items=>[{sex,id:concept.id,name:concept.name},...items.filter(item=>!(item.sex===sex&&item.id===concept.id))].slice(0,8)),[sex]);
 const choose=useCallback((concept:Concept)=>{rememberRecent(concept);setChosen(concept);setInfoSystem(null);setState(s=>({...s,selected:concept.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);setAbout(false);writeShareUrl(sex,concept.name);notifyParent({type:'selection',sex,id:concept.id,name:concept.name,url:window.location.href});announce(`Selected ${concept.name}. ${concept.elements.length.toLocaleString()} modeled pieces.`);},[announce,rememberRecent,sex]);
 const choosePart=useCallback((id:string)=>{const part=parts.get(id);if(!part)return;const concept=atlas?.concepts.find(c=>c.id===part.conceptId)??{id:part.conceptId,name:part.name,elements:[id]};rememberRecent(concept);setChosen({id:concept.id,name:concept.name,elements:[id]});setInfoSystem(null);setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);setAbout(false);writeShareUrl(sex,concept.name);notifyParent({type:'selection',sex,id:concept.id,name:concept.name,url:window.location.href});announce(`Selected ${concept.name}.`);},[announce,atlas,parts,rememberRecent,sex]);
 useEffect(()=>{if(!atlas)return;const params=new URLSearchParams(window.location.search),requested=params.get('structure'),key=`${sex}:${requested??''}`;if(deepLinkKey.current===key)return;deepLinkKey.current=key;if(!requested)return;const concept=findConcept(atlas,requested);if(concept){choose(concept);if(params.get('isolate')==='1')setState(s=>({...s,isolate:true}));}else announce(`The structure “${requested}” is not present in this edition.`);},[atlas,choose,sex,announce]);
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas,choose]);
 const closeDetail=useCallback(()=>{setDetails(false);setInfoSystem(null);},[]);
 const openSystemInfo=useCallback((id:SystemId)=>{const item=SYSTEMS.find(s=>s.id===id);if(!item)return;setInfoSystem(id);setDetails(false);setChosen(null);setPanel(null);setAbout(false);setState(s=>({...s,isolate:false,selected:[]}));writeShareUrl(sex);announce(`${item.name}: ${item.description}`);},[announce,sex]);
 const changeEdition=(value:string|null)=>{if(value!=='male'&&value!=='female')return;const next=value as Sex;if(next===sex)return;setSex(next);clearStateParams();writeShareUrl(next);setAnnouncement(`${edition(next).label} reference selected. Loading its anatomy.`);};
 const setVisible=(visible:SystemId[],label:string)=>{const next=visible.filter(id=>activeSystems.some(systemItem=>systemItem.id===id));setState(s=>({...s,visible:next}));announce(`${label} preset applied. ${next.length} systems visible.`);};
 const applyPreset=(preset:LearningPreset)=>setVisible(preset.id==='overview'?defaultVisible(sex):preset.systems,preset.label);
 const toggle=(id:SystemId)=>{const enabled=state.visible.includes(id);setDetails(false);setInfoSystem(null);setState(s=>({...s,selected:[],isolate:false,visible:enabled?s.visible.filter(x=>x!==id):[...s.visible,id]}));announce(`${enabled?'Hidden':'Showing'} ${SYSTEMS.find(s=>s.id===id)?.name??'system'}.`);};
 const reset=()=>{setState(s=>({...initial(sex),reset:s.reset+1}));setChosen(null);setDetails(false);setInfoSystem(null);setPanel(null);announce('View and layers reset.');};
 const openPanel=useCallback((next:'layers'|'search')=>{setDetails(false);setInfoSystem(null);setPanel(current=>current===next?null:next);},[]);
 const dismissGuide=()=>{setGuide(false);try{localStorage.setItem(GUIDE_KEY,'dismissed');}catch{}announce('Quick start guide dismissed.');};
 const copyLink=async()=>{try{await navigator.clipboard.writeText(window.location.href);setCopied(true);announce('Share link copied.');window.setTimeout(()=>setCopied(false),1800);}catch{announce('Could not copy the share link on this device.');}};
 useEffect(()=>{const key=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null;if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target?.isContentEditable)return;if(event.key==='/'){event.preventDefault();setPanel('search');closeDetail();return;}if(event.key==='Escape'){setPanel(null);closeDetail();setAbout(false);if(guide)dismissGuide();return;}const shortcuts:Record<string,View>={q:'three-quarter','0':'three-quarter','1':'front','2':'side','3':'back'};const view=shortcuts[event.key.toLowerCase()];if(view){setState(s=>({...s,view,reset:s.reset+1,rotate:false}));announce(`${view} view selected.`);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[announce,closeDetail,dismissGuide,guide]);
 const orientation=state.view==='back'?{anterior:'Posterior',posterior:'Anterior',left:'Right',right:'Left'}:{anterior:'Anterior',posterior:'Posterior',left:'Left',right:'Right'};
 const showOrientation=state.view!=='three-quarter'&&state.explode<=.05&&!state.isolate;
 const infoCount=infoSystem?counts[infoSystem]:0;
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:detailOpen}} theme={theme} onSelect={choosePart} onProgress={setProgress} onReady={()=>{setProgress(100);setError('');notifyParent({type:'ready'});}} onError={setError}/>}<div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> INTERACTIVE 3D EXPLORER</div><h1 className="brand-heading"><a href="https://testwiz.ng/medical" target="_blank" rel="noreferrer" aria-label="Open Testwiz Medical"><img src="/brand/testwiz-main-logo.webp" alt="Testwiz"/><span>Anatomy</span><Badge variant="outline" className="edition">3D</Badge></a></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():(sex==='male'?'2,234':'—')} modeled pieces <span>·</span> {source.dataset}</div><div className="anatomy-choice"><Select value={sex} onValueChange={changeEdition}><SelectTrigger aria-label="Reference body edition"><span>{source.label} reference body</span></SelectTrigger><SelectContent className="anatomy-choice-menu">{EDITIONS.map(item=><SelectItem key={item.sex} value={item.sex}>{item.label} reference body</SelectItem>)}</SelectContent></Select></div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>{setInfoSystem(null);setPanel(panel==='search'?null:'search');}} aria-label="Search anatomy"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="About this atlas" onClick={()=>{closeDetail();setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Anatomical layers">
   <div className="panel-heading"><span>Systems</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close systems"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(item=>state.visible.includes(item.id))} onClick={()=>setVisible(activeSystems.map(item=>item.id),'All')}>All</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setVisible(['skeletal'],'Skeleton')}>Skeleton</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setVisible(['cardiac','respiratory','digestive','urinary','endocrine','reproductive'],'Organs')}>Organs</Button></div>
   <div className="layer-presets curated-presets" aria-label="Learning presets">{LEARNING_PRESETS.map(preset=><Button variant="ghost" key={preset.id} aria-label={`${preset.label}: ${preset.description}`} onClick={()=>applyPreset(preset)}>{preset.label}</Button>)}</div>
   <div className="system-list">{activeSystems.map(item=><div className={`system-row ${state.visible.includes(item.id)?'enabled':''}`} key={item.id}><Button variant="ghost" className="system-name" title={`Show only ${item.name.toLowerCase()}`} onClick={()=>setState(value=>({...value,visible:[item.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:item.color}}/>{item.name}<span className="system-count">{counts[item.id]}</span></Button><Button variant="ghost" className="system-info icon-button" aria-label={`Explain ${item.name.toLowerCase()}`} onClick={event=>{event.stopPropagation();openSystemInfo(item.id);}}><Info size={14}/></Button><Switch checked={state.visible.includes(item.id)} onCheckedChange={()=>toggle(item.id)} aria-label={`Show ${item.name.toLowerCase()}`} /></div>)}</div>
   {sex==='female'&&state.visible.includes('integumentary')&&<div className="surface-opacity-control"><div className="surface-opacity-label"><span>Surface opacity</span><output>{Math.round(state.surfaceOpacity*100)}%</output></div><Slider aria-label="Body surface opacity" min={5} max={60} step={1} value={[Math.round(state.surfaceOpacity*100)]} onValueChange={value=>{const next=(Array.isArray(value)?value[0]:value)/100;setState(s=>({...s,surfaceOpacity:next}));announce(`Body surface opacity ${Math.round(next*100)} percent.`);}}/></div>}
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Hide all</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div>{!query&&recentForEdition.length>0&&<div className="recent-structures"><div className="recent-heading"><span>Recent structures</span><span>{recentForEdition.length}</span></div>{recentForEdition.map(entry=><Button variant="ghost" className="recent-item" key={`${entry.sex}:${entry.id}`} onClick={()=>{const concept=atlas&&findConcept(atlas,entry.id);if(concept)choose(concept);}}><Clock3 size={14}/><span>{entry.name}</span><ChevronRight size={14}/></Button>)}</div>}<Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={item=>item.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Heart, femur, cranial nerve…" aria-label="Search named anatomical structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(concept:Concept)=><ComboboxItem key={concept.id} value={concept}><span className="search-result-name">{concept.name}</span><span className="small-number">{concept.elements.length} {concept.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  {showOrientation&&<div className={`orientation-labels orientation-${state.view}`} aria-label={`Orientation: ${orientation.anterior}, ${orientation.posterior}, ${orientation.left}, ${orientation.right}`} role="note"><span className="orientation-anterior">{orientation.anterior}</span><span className="orientation-posterior">{orientation.posterior}</span><span className="orientation-left">{orientation.left}</span><span className="orientation-right">{orientation.right}</span></div>}
  {atlas&&guide&&<aside className="first-use-guide" role="dialog" aria-label="Quick start guide"><div className="first-use-guide-header"><div><div className="eyebrow">QUICK START</div><h2>Explore the atlas</h2></div><Button variant="ghost" className="icon-button" aria-label="Dismiss quick start guide" onClick={dismissGuide}><X size={17}/></Button></div><ul><li><span>Drag</span> to orbit</li><li><span>Scroll / pinch</span> to zoom</li><li><span>Tap</span> a structure to inspect it</li><li>Press <kbd>/</kbd> to search</li><li>Switch between male and female editions</li></ul><Button variant="ghost" className="guide-dismiss" onClick={dismissGuide}>Got it</Button></aside>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((view,index)=>{const shortcut=['0','1','2','3'][index];return <Button variant="ghost" key={view} className={state.view===view?'active':''} aria-pressed={state.view===view} aria-keyshortcuts={shortcut} disabled={state.explode>.8&&view!=='front'} onClick={()=>{setState(s=>({...s,view,reset:s.reset+1,rotate:false}));announce(`${view} view selected.`);}} title={`${view} view (${shortcut})`} aria-label={`${view} view`}><span>{['¾','F','S','B'][index]}</span></Button>;})}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':source.caption}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>{setInfoSystem(null);openPanel('layers');}} aria-label="Open system layers"><Layers3 size={20}/><span>Systems</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode anatomy</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={value=>setState(s=>({...s,explode:(Array.isArray(value)?value[0]:value)/100,view:(Array.isArray(value)?value[0]:value)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Drag to pan':'Drag to orbit'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect</span><Button variant="ghost" onClick={()=>{closeDetail();setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></footer>
  <div className="sr-only" role="status" aria-live="polite">{announcement}</div>
  {progress<100&&!error&&<div className="loading glass" role="status" aria-live="polite"><Activity size={18}/><div><strong>Preparing the {source.label.toLowerCase()} anatomy</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??(sex==='male'?'2,234':'—')} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={detailOpen} modal={false} disablePointerDismissal onOpenChange={open=>{if(!open)closeDetail();}}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:info?.color??system?.color}}/><div className="eyebrow">{info?.name??system?.name??'ANATOMY'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{info?.name??chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${infoSystem??chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{info?.description??(chosen&&selected?explanation(chosen.name,selected.system):'')}</SheetDescription>{info?<span className="context-note">{source.limits}</span>:chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">System overview · structure identified from source anatomy</span>}{info?<div className="structure-meta"><span>Modeled pieces<strong>{infoCount.toLocaleString()}</strong></span><span>Reference<strong>{source.dataset}</strong></span></div>:<div className="structure-meta"><span>Atlas reference<strong>{chosen?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span></div>}{!info&&selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(part=><Button variant="ghost" key={part.id} onClick={()=>choosePart(part.id)}><span>{part.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled pieces.</p>}</div>}<a className="source-link" href={source.download} target="_blank" rel="noreferrer">View anatomical source <ArrowUpRight size={14}/></a></div><div className="detail-actions">{info&&infoSystem?<Button className="primary-action" onClick={()=>{setState(s=>({...s,visible:[infoSystem]}));announce(`Showing only ${info.name.toLowerCase()}.`);closeDetail();}}><Layers3 size={18}/>Show only {info.name}<ChevronRight size={16}/></Button>:<Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Show surrounding anatomy':'Isolate structure'}<ChevronRight size={16}/></Button>}<Button variant="ghost" className="secondary-action" onClick={copyLink}><Share2 size={15}/>{copied?'Copied':'Copy share link'}</Button>{info?<Button variant="ghost" className="secondary-action" onClick={closeDetail}>Close</Button>:<Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));closeDetail();}}>Clear selection</Button>}</div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">SOURCE & SCOPE</div><SheetTitle className="structure-title">About Testwiz Anatomy</SheetTitle><SheetDescription>Explore the {source.label.toLowerCase()} reference anatomy from {source.dataset}.</SheetDescription><div className="about-copy"><p><strong>{source.label} · {source.dataset}</strong><br/>{source.summary}</p><p>{source.limits}</p><p>Colors and system groupings are designed for exploration. The geometry is simplified for the web, and short explanations provide general educational context. Testwiz Anatomy is an educational reference, not a diagnostic or surgical tool.</p><h3>Source</h3><p>{source.credit}</p><a href={source.licence} target="_blank" rel="noreferrer">Dataset license <ArrowUpRight size={14}/></a><a href={source.download} target="_blank" rel="noreferrer">Original geometry & metadata <ArrowUpRight size={14}/></a>{source.supplement&&<a href={source.supplement} target="_blank" rel="noreferrer">Pelvic supplement (v1.5) <ArrowUpRight size={14}/></a>}{source.publication&&<a href={source.publication} target="_blank" rel="noreferrer">Read the source publication <ArrowUpRight size={14}/></a>}</div></SheetContent></Sheet>
 </main>;
}
